### ISSUE TITLE
error in installer

### ISSUE THREAD

**Issue by endquote** [coollabsio/get.coollabs.io#7]
I'm trying to install on a new Ubuntu 20.04.4 VM.

I ran: `sudo sh -c "$(curl -fsSL https://get.coollabs.io/coolify/install.sh)"`

I get: `sh: 13: set: Illegal option -o pipefail`

Should I be using a different OS distro or version?

**Comment by andrasbacsai** [comment]
Hey. You should use the official way to install Coolify:

`/bin/bash -c "$(curl -fsSL https://get.coollabs.io/coolify/install.sh)"`

Using `sh` is not the same as using `bash`. `sh` could link to a different shell with different built-in commands.
Let me know if the official way is not working!

I plan to have support for different OS distros/versions.

**Comment by endquote** [comment]
When I use that command I get this:

```
cat: /proc/sys/kernel/random/uuid: No such file or directory
/bin/bash: line 5: sha256sum: command not found
/bin/bash: line 5: 1649096218N: value too great for base (error token is "1649096218N")
Welcome to Coolify installer!
This script will install all the required packages and services to run Coolify.\n

Currently only Ubuntu is supported. If you want to install Coolify on a different OS, please open an issue on Github to get supported version.
To see what this script is doing, you can check it here: https://github.com/coollabsio/get.coollabs.io/blob/main/static/coolify/install.sh

Run as root please: sudo sh -c "$(curl -fsSL https://get.coollabs.io/coolify/install.sh)"
/bin/bash exited unexpectedly with status: 1
```

That's why I used the other one.
